[package]
name = "disturb_shared"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
bevy_networking_turbulence = { version = "0.3.0", default-features = false, features = ["use-webrtc"] }
bevy = { version = "0.5.0", default-features = false }
